[workspace]
members = [
    "contracts/increment",
    "contracts/hello_world"
]

resolver = "2"

[patch.crates-io]
soroban-env-host = { git = "https://github.com/stellar/soroban-env", branch = "main", version = "=22.1.2" }

